### ISSUE TITLE
Build fails on archlinux, can't copy mo file...

### ISSUE THREAD

**Issue by mmetak** [eLvErDe/nicotine-plus#22] opened 2016-08-21 02:50 UTC
`error: can't copy 'languages/lt/nicotine.mo': doesn't exist or not a regular file`
And for some reason it thinks it's on windows?
` /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'windows'`

What could I be doing wrong?

**Comment by gfarmerfr** [comment] 2016-08-21 10:44
HI @mmetak 

I suppose your using the AUR nicotine-plus-git package ?
Setuptools needed a good refresh.
It's now done on git master and should hopefully fix your problem.
Could you retry to install it ?

**Comment by mmetak** [comment] 2016-08-21 23:01
```
pon 01:00 Translation for 'sl' not found, falling back to english
pon 01:00 Cannot set the locale: unsupported locale setting, falling back to
          english
Traceback (most recent call last):
  File "/usr/bin/nicotine.py", line 36, in <module>
    ApplyTranslation()
  File "/usr/lib/python2.7/site-packages/pynicotine/utils.py", line 174, in ApplyTranslation
    SetLocaleEnv("en")
  File "/usr/lib/python2.7/site-packages/pynicotine/libi18n.py", line 158, in SetLocaleEnv
    locale.setlocale(locale.LC_ALL, 'C.UTF-8')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```
It builds fine, but fails to start with this error?

**Comment by gfarmerfr** [comment] 2016-08-22 07:52
HI @mmetak 

Great to know i've fixed the first problem.
I've tried too reproduce this problem on a ubuntu VM install in the 'sl' lang but i can't reproduce the error.
Can you post me the return of a `locale -a` command from a terminal ?

**Comment by mmetak** [comment] 2016-08-22 08:03
Hello @gfarmerfr

It appears nicotine failed to start because it was trying to fallback to English and I didn't have it enabled. So after editing `/etc/locale.gen` , enabling English and re-generating the locales, nicotine starts now. ;-)

**Comment by gfarmerfr** [comment] 2016-08-22 10:54
@mmetak : That's what i was suspecting :)
In distro like arch or gentoo, since people can do almost anything (which is great btw) and are asked to configure their locales by hand this can happen. I need to take care of that.

At this time if i don't find translation for your current locale I try setting the locale to en_US.UTF-8 and if this fails too, as a last resort i'm trying to set the locale to C.UTF-8.
I think both of them were failing/missing in your case.

I've tested a few more things and I think the best course of action is to not even try to change the locales if there's no translation for your language. Gettext will not translate and stay in English, Glade will fallback to C as I've seen.

If i see any other bug report like yours that's what i will do.

Anyway, could we close this one ?

**Closed** 2016-08-22 12:43 UTC
Labels: bug
